#pragma once
#include <Unicode/string.h>
#include <Unicode/exceptions.h>
#include <Utilities/inttypes.h>
#include <Utilities/pretty_print.h>
#include <Utilities/string.h>
#include <Utilities/containers.h>
#include <Utilities/assert.h>
#include <iostream>
#include <vector>
#include <map>
#include <set>

using std::vector;
using std::map;
using std::set;
using std::wcin;
using std::wcout;
using std::wcerr;
using std::endl;
using std::flush;
